<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>TaskPatternExample7</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\AbstractTask\AbstractTask.csproj" />
    </ItemGroup>

</Project>
